"""initial schema: exact decimals, provenance, research runs and review, plans

Revision ID: 4b3dcb0cd928
Revises: 
Create Date: 2026-09-18 13:35:52.991753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import packages.database.types  # noqa: F401  (ExactDecimal)


# revision identifiers, used by Alembic.
revision: str = '4b3dcb0cd928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_status',
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_age_hours', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('macro_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('value', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'observation_date', 'label')
    )
    op.create_index(op.f('ix_macro_observations_observation_date'), 'macro_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_macro_observations_series_id'), 'macro_observations', ['series_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_inputs',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('local_ticker', sa.String(length=16), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_bank', sa.Boolean(), nullable=False),
    sa.Column('industry_template', sa.String(length=20), nullable=False),
    sa.Column('listing_status', sa.String(length=20), nullable=False),
    sa.Column('listing_url', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'local_ticker')
    )
    op.create_index(op.f('ix_securities_exchange'), 'securities', ['exchange'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('feature', sa.String(length=80), nullable=False),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature')
    )
    op.create_index(op.f('ix_entitlements_plan_id'), 'entitlements', ['plan_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_sha256', sa.String(length=64), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_security_id'), 'research_runs', ['security_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('published_on_evidence', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_security_id'), 'source_documents', ['security_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('validation_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=80), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('expected', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=True),
    sa.Column('actual', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_checks_security_id'), 'validation_checks', ['security_id'], unique=False)
    op.create_table('extraction_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value_a', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=True),
    sa.Column('source_a', sa.String(length=200), nullable=False),
    sa.Column('value_b', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=True),
    sa.Column('source_b', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_conflicts_security_id'), 'extraction_conflicts', ['security_id'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=8), nullable=False),
    sa.Column('item_code', sa.String(length=60), nullable=False),
    sa.Column('label_as_reported', sa.String(length=300), nullable=False),
    sa.Column('value', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('column_role', sa.String(length=12), nullable=False),
    sa.Column('extraction_method', sa.String(length=60), nullable=False),
    sa.Column('agreed_by', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'fiscal_year', 'item_code', 'document_id', 'column_role')
    )
    op.create_index(op.f('ix_financial_facts_fiscal_year'), 'financial_facts', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_facts_item_code'), 'financial_facts', ['item_code'], unique=False)
    op.create_index(op.f('ix_financial_facts_security_id'), 'financial_facts', ['security_id'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('volume', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'trade_date')
    )
    op.create_index(op.f('ix_price_bars_instrument_id'), 'price_bars', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_price_bars_trade_date'), 'price_bars', ['trade_date'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_run_id'), 'review_events', ['run_id'], unique=False)
    op.create_table('risk_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_items_security_id'), 'risk_items', ['security_id'], unique=False)
    op.create_table('saved_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_weights_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('weight', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', packages.database.types.ExactDecimal(precision=28, scale=10), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['saved_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_holdings')
    op.drop_table('saved_portfolios')
    op.drop_index(op.f('ix_risk_items_security_id'), table_name='risk_items')
    op.drop_table('risk_items')
    op.drop_index(op.f('ix_review_events_run_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_price_bars_trade_date'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_instrument_id'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_financial_facts_security_id'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_item_code'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_fiscal_year'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_extraction_conflicts_security_id'), table_name='extraction_conflicts')
    op.drop_table('extraction_conflicts')
    op.drop_index(op.f('ix_validation_checks_security_id'), table_name='validation_checks')
    op.drop_table('validation_checks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_documents_security_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_research_runs_security_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_entitlements_plan_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_securities_exchange'), table_name='securities')
    op.drop_table('securities')
    op.drop_table('reference_inputs')
    op.drop_table('plans')
    op.drop_index(op.f('ix_macro_observations_series_id'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_observation_date'), table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_table('data_source_status')
    # ### end Alembic commands ###
